test/data/err_XYZ_100.py:3:1 [XYZ100]: Your message here
